# Generated by Django 5.0 on 2024-05-03 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=300, verbose_name="Город")),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="ProfileTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Телеграм ID"
                    ),
                ),
                ("fullname", models.TextField(verbose_name="Полное имя")),
                ("username", models.TextField(verbose_name="Телеграм юзернейм")),
                (
                    "contacts",
                    models.CharField(
                        max_length=13, unique=True, verbose_name="Контакты"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано в"),
                ),
                (
                    "fullname_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обнавлен в"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь телеграма",
                "verbose_name_plural": "Пользователи телеграма",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название категории"),
                ),
                (
                    "emojis",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Эмоджи для категории",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Картинки категорий",
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="store.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        default="", max_length=250, verbose_name="Имя покупателя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        default="", max_length=250, verbose_name="Фамилия покупателя"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "user_telegram",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.profiletelegram",
                        verbose_name="Пользователь телеграма",
                    ),
                ),
            ],
            options={
                "verbose_name": "Покупатель",
                "verbose_name_plural": "Покупатели",
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Название почты"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Почта",
                "verbose_name_plural": "Почтовые Адреса",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Заказ выполнен"),
                ),
                (
                    "shipping",
                    models.BooleanField(default=True, verbose_name="Доставка"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.customer",
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название продукта"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Количество товара"),
                ),
                (
                    "description",
                    models.TextField(
                        default="Описание скоро будит", verbose_name="Описание товара"
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                ("size", models.IntegerField(default=30, verbose_name="Размер")),
                (
                    "color",
                    models.CharField(
                        default="Серебро", max_length=30, verbose_name="Цвет/Материал"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="OrderProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Количество"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказанный товар",
                "verbose_name_plural": "Заказанные товары",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Картинки продуктов"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка",
                "verbose_name_plural": "Картинки",
            },
        ),
        migrations.CreateModel(
            name="ProductTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название продукта"),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(default=0, verbose_name="Количество товара"),
                ),
                (
                    "description",
                    models.TextField(
                        default="Описание скоро будет", verbose_name="Описание товара"
                    ),
                ),
                ("slug", models.SlugField(null=True, unique=True)),
                ("size", models.IntegerField(default=30, verbose_name="Размер")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_telegrams",
                        to="store.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар телеграм",
                "verbose_name_plural": "Товары телеграм",
            },
        ),
        migrations.CreateModel(
            name="GalleryTelegram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/", verbose_name="Картинки продуктов"
                    ),
                ),
                ("color", models.CharField(max_length=100, verbose_name="Цвет")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="store.producttelegram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка телеграм",
                "verbose_name_plural": "Картинки телеграм",
            },
        ),
        migrations.CreateModel(
            name="FavoriteProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="Продукт избранного",
                    ),
                ),
                (
                    "user_telegram",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.profiletelegram",
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Отзыв покупателя")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата отзыва"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="Продукт отзыва",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.CreateModel(
            name="SaveOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заказа"),
                ),
                (
                    "total_price",
                    models.FloatField(default=0, verbose_name="Сумма заказа"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.customer",
                        verbose_name="Покупатель",
                    ),
                ),
            ],
            options={
                "verbose_name": "История заказа",
                "verbose_name_plural": "Истории заказов",
            },
        ),
        migrations.CreateModel(
            name="SaveOrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=400, verbose_name="Товар")),
                ("quantity", models.IntegerField(default=0, verbose_name="Количество")),
                ("product_price", models.FloatField(verbose_name="Цена товара")),
                ("final_price", models.FloatField(verbose_name="На сумму")),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата покупки"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="images/", verbose_name="Фото товара"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="store.saveorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "История заказанного товара",
                "verbose_name_plural": "Истории заказанных товаров",
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=300, verbose_name="Адрес (ул, дом, кв)"
                    ),
                ),
                ("region", models.CharField(max_length=300, verbose_name="Регион")),
                (
                    "phone",
                    models.CharField(max_length=250, verbose_name="Номер телефона"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата доставки"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.city",
                        verbose_name="Город",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.customer",
                        verbose_name="Покупатель",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="store.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Адрес доставки",
                "verbose_name_plural": "Адреса доставок",
            },
        ),
    ]
